name: Deploy to Dev Environment

on:
  workflow_run:
    workflows: ["Docker Build Test"]
    types:
      - completed
    branches:
      - main

jobs:
  create-dev-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download workflow artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: commit-sha-${{ github.event.workflow_run.id }}
          pattern: commit-sha.txt

      - name: Extract commit SHA
        id: extract-commit
        run: |
          echo "sha=$(cat commit-sha.txt)" >> $GITHUB_OUTPUT
          echo "Using commit: $(cat commit-sha.txt)"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ steps.extract-commit.outputs.sha }}

      - name: Tag successful Dev deployment
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Create a dev tag for this commit
          # This tag format (dev/timestamp) is recognized by the environment-promotion workflow
          # as the source for promotions to devnet
          CURRENT_DATE=$(date +%Y%m%d%H%M%S)
          COMMIT_SHA="${{ steps.extract-commit.outputs.sha }}"
          git tag -a dev/$CURRENT_DATE -m "Dev deployment from ${COMMIT_SHA}"
          git push origin dev/$CURRENT_DATE
          echo "Created tag dev/$CURRENT_DATE for commit ${COMMIT_SHA}"