name: Deploy to Dev Environment

on:
  workflow_run:
    workflows: ["Docker Build Test"]
    types:
      - completed
    branches:
      - main

jobs:
  create-dev-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.workflow_run.head_commit.id }}

      - name: Tag successful Dev deployment
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Create a dev tag for this commit
          # This tag format (dev/timestamp) is recognized by the environment-promotion workflow
          # as the source for promotions to devnet
          CURRENT_DATE=$(date +%Y%m%d%H%M%S)
          COMMIT_SHA=$(git rev-parse --short=8 HEAD)
          git tag -a dev/$CURRENT_DATE -m "Dev deployment from ${COMMIT_SHA}"
          git push origin dev/$CURRENT_DATE
          echo "Created tag dev/$CURRENT_DATE for commit ${COMMIT_SHA}"