name: Docker Build Test

env:
  REPO_NAME: astriaorg/astria-release-test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git branch, or tag to build from.
        required: false
      target:
        description: Target to build.
        required: false
        type: choice
        options:
          - auctioneer
          - composer
          - conductor
          - sequencer
          - sequencer-relayer
          - evm-bridge-withdrawer
          - cli
  merge_group:
  push:
    branches:
      - "main"
    tags:
      - "**-v[0-9]+.[0-9]+.[0-9]+"
      - "**-v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "**-v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "**-v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  run_checker:
    uses: ./.github/workflows/reusable-run-checker.yml

  auctioneer:
    needs: run_checker
    if: needs.run_checker.outputs.run_docker == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'auctioneer')
    uses: "./.github/workflows/reusable-docker-build.yml"
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      depot-project-id: 0q41v32h7j
      package-name: auctioneer
      binary-name: auctioneer
      tag: ${{ inputs.tag }}
      force: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'auctioneer' }}
      # Add suffix for test images
      image-suffix: release-test
    secrets: inherit

  composer:
    needs: run_checker
    if: needs.run_checker.outputs.run_docker == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'composer')
    uses: "./.github/workflows/reusable-docker-build.yml"
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      depot-project-id: 0q41v32h7j
      package-name: composer
      binary-name: composer
      tag: ${{ inputs.tag }}
      force: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'composer' }}
      # Add suffix for test images
      image-suffix: release-test
    secrets: inherit

  conductor:
    needs: run_checker
    if: needs.run_checker.outputs.run_docker == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'conductor')
    uses: "./.github/workflows/reusable-docker-build.yml"
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      depot-project-id: 0q41v32h7j
      package-name: conductor
      binary-name: conductor
      tag: ${{ inputs.tag }}
      force: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'conductor' }}
      # Add suffix for test images
      image-suffix: release-test
    secrets: inherit

  sequencer:
    needs: run_checker
    if: needs.run_checker.outputs.run_docker == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'sequencer')
    uses: "./.github/workflows/reusable-docker-build.yml"
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      depot-project-id: 0q41v32h7j
      package-name: sequencer
      binary-name: sequencer
      tag: ${{ inputs.tag }}
      force: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'sequencer' }}
      # Add suffix for test images
      image-suffix: release-test
    secrets: inherit

  sequencer-relayer:
    needs: run_checker
    if: needs.run_checker.outputs.run_docker == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'sequencer-relayer')
    uses: "./.github/workflows/reusable-docker-build.yml"
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      depot-project-id: 0q41v32h7j
      package-name: sequencer-relayer
      binary-name: sequencer-relayer
      tag: ${{ inputs.tag }}
      force: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'sequencer-relayer' }}
      # Add suffix for test images
      image-suffix: release-test
    secrets: inherit

  evm-bridge-withdrawer:
    needs: run_checker
    if: needs.run_checker.outputs.run_docker == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'evm-bridge-withdrawer')
    uses: "./.github/workflows/reusable-docker-build.yml"
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      depot-project-id: 0q41v32h7j
      package-name: evm-bridge-withdrawer
      binary-name: bridge-withdrawer
      tag: ${{ inputs.tag }}
      force: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'evm-bridge-withdrawer' }}
      # Add suffix for test images
      image-suffix: release-test
    secrets: inherit

  cli:
    needs: run_checker
    if: needs.run_checker.outputs.run_docker == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'cli')
    uses: "./.github/workflows/reusable-docker-build.yml"
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      depot-project-id: 0q41v32h7j
      package-name: astria-cli
      binary-name: cli
      tag: ${{ inputs.tag }}
      # Add suffix for test images
      image-suffix: release-test
    secrets: inherit

  smoke-test:
    needs: [run_checker, composer, conductor, sequencer, sequencer-relayer, evm-bridge-withdrawer, cli]
    # TODO: (flip this back when merge to main repo) github.event.pull_request.head.repo.fork == false) &&
    if: |
      (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == true) &&
      (github.event_name == 'merge_group' || needs.run_checker.outputs.run_docker == 'true')
    runs-on: depot-ubuntu-24.04-8
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Smoke Test Environment
        timeout-minutes: 10
        run: |
          TAG=sha-$(git rev-parse --short HEAD)
          just deploy cluster
          kubectl create secret generic regcred --from-file=.dockerconfigjson=$HOME/.docker/config.json --type=kubernetes.io/dockerconfigjson
          echo -e "\n\nDeploying with astria images tagged $TAG"
          just deploy smoke-test $TAG
      - name: Run Smoke test
        timeout-minutes: 3
        run: |
          TAG=sha-$(git rev-parse --short HEAD)
          just run-smoke-test $TAG
  smoke-cli:
    needs: [run_checker, composer, conductor, sequencer, sequencer-relayer, evm-bridge-withdrawer, cli]
    # TODO: (flip this back when merge to main repo) github.event.pull_request.head.repo.fork == false) &&
    if: |
      (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == true) &&
      (github.event_name == 'merge_group' || needs.run_checker.outputs.run_docker == 'true')
    runs-on: depot-ubuntu-24.04-8
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Smoke Test Environment
        timeout-minutes: 5
        run: |
          TAG=sha-$(git rev-parse --short HEAD)
          just deploy cluster
          kubectl create secret generic regcred --from-file=.dockerconfigjson=$HOME/.docker/config.json --type=kubernetes.io/dockerconfigjson
          echo -e "\n\nDeploying with astria images tagged $TAG"
          just deploy smoke-cli $TAG
      - name: Run Smoke test
        timeout-minutes: 3
        run: |
          TAG=sha-$(git rev-parse --short HEAD)
          just run-smoke-cli $TAG

  ibc-bridge-test:
    needs: [ run_checker, composer, conductor, sequencer, sequencer-relayer, evm-bridge-withdrawer, cli ]
    # TODO: (flip this back when merge to main repo) github.event.pull_request.head.repo.fork == false) &&
    if: |
      (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == true) &&
      (github.event_name == 'merge_group' || needs.run_checker.outputs.run_docker == 'true')
    runs-on: depot-ubuntu-24.04-8
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup IBC Bridge Test Environment
        timeout-minutes: 8
        run: |
          TAG=sha-$(git rev-parse --short HEAD)
          just deploy cluster
          kubectl create secret generic regcred --from-file=.dockerconfigjson=$HOME/.docker/config.json --type=kubernetes.io/dockerconfigjson
          echo -e "\n\nDeploying with astria images tagged $TAG"
          just ibc-test deploy $TAG
      - name: Run IBC ICS20 Transfer test
        timeout-minutes: 3
        run: |
          TAG=sha-$(git rev-parse --short HEAD)
          just ibc-test run $TAG

  ibc-no-native-asset-test:
    needs: [ run_checker, composer, conductor, sequencer, sequencer-relayer, evm-bridge-withdrawer, cli ]
    # TODO: (flip this back when merge to main repo) github.event.pull_request.head.repo.fork == false) &&
    if: |
      (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == true) &&
      (github.event_name == 'merge_group' || needs.run_checker.outputs.run_docker == 'true')
    runs-on: depot-ubuntu-24.04-8
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup IBC Bridge Test Environment
        timeout-minutes: 8
        run: |
          TAG=sha-$(git rev-parse --short HEAD)
          just deploy cluster
          kubectl create secret generic regcred --from-file=.dockerconfigjson=$HOME/.docker/config.json --type=kubernetes.io/dockerconfigjson
          echo -e "\n\nDeploying with astria images tagged $TAG"
          just ibc-test deploy-without-native $TAG
      - name: Run IBC utia as native test
        timeout-minutes: 3
        run: |
          TAG=sha-$(git rev-parse --short HEAD)
          just ibc-test run-without-native $TAG

  ibc-timeout-refund:
    needs: [ run_checker, composer, conductor, sequencer, sequencer-relayer, evm-bridge-withdrawer, cli ]
    # TODO: (flip this back when merge to main repo) github.event.pull_request.head.repo.fork == false) &&
    if: |
      (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == true) &&
      (github.event_name == 'merge_group' || needs.run_checker.outputs.run_docker == 'true')
    runs-on: depot-ubuntu-24.04-8
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup IBC Bridge Test Environment
        timeout-minutes: 8
        run: |
          TAG=sha-$(git rev-parse --short HEAD)
          just deploy cluster
          kubectl create secret generic regcred --from-file=.dockerconfigjson=$HOME/.docker/config.json --type=kubernetes.io/dockerconfigjson
          echo -e "\n\nDeploying with astria images tagged $TAG"
          just ibc-test deploy-timeout $TAG
      - name: Run IBC ICS20 Transfer test
        timeout-minutes: 3
        run: |
          TAG=sha-$(git rev-parse --short HEAD)
          just ibc-test run-timeout $TAG

  docker:
    if: ${{ always() && !cancelled() }}
    needs: [auctioneer, composer, conductor, sequencer, sequencer-relayer, evm-bridge-withdrawer, cli, smoke-test, smoke-cli, ibc-bridge-test, ibc-no-native-asset-test, ibc-timeout-refund]
    uses: ./.github/workflows/reusable-success.yml
    with:
      success: ${{ !contains(needs.*.result, 'failure') }}

  # This job creates dev/* tags for successful builds on main branch
  # These tags are essential for the environment promotion workflow (.github/workflows/environment-promotion.yml)
  # The promotion path is: dev -> devnet -> testnet -> mainnet
  # When promoting to devnet, the workflow looks for the latest dev/* tag
  # without this job, there would be no dev/* tags to find when promoting to devnet
  deploy-to-dev:
    needs: [smoke-test, smoke-cli, ibc-bridge-test, ibc-no-native-asset-test, ibc-timeout-refund]
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      !contains(needs.*.result, 'failure')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag successful Dev deployment
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Create a dev tag for this commit
          # This tag format (dev/timestamp) is recognized by the environment-promotion workflow
          # as the source for promotions to devnet
          CURRENT_DATE=$(date +%Y%m%d%H%M%S)
          git tag -a dev/$CURRENT_DATE -m "Dev deployment from ${{ github.sha }}"
          git push origin dev/$CURRENT_DATE
          echo "Created tag dev/$CURRENT_DATE for commit ${{ github.sha }}"