name: Reusable Docker Build && Push Workflow

on:
  workflow_call:
    inputs:
      depot-project-id:
        required: true
        type: string
      package-name:
        required: true
        type: string
      binary-name:
        required: true
        type: string
      binary-prefix:
        type: string
        default: astria
      tag:
        required: false
        type: string
      force:
        required: false
        type: boolean
        default: false
      # INFRA-MAR-25: Add new input parameter for image suffix
      image-suffix:
        type: string
        default: ""
        required: false
    secrets:
      DOCKER_TOKEN:
        required: false
      DOCKER_USER:
        required: false
env:
  REPO_NAME: astriaorg/astria-release-test
  REPO_ORG: astriaorg
  REGISTRY: ghcr.io
  FULL_REF: ${{ inputs.tag && format('refs/tags/{0}', inputs.tag) || github.ref }}
  FULL_BINARY_NAME: ${{ inputs.binary-prefix }}-${{ inputs.binary-name }}
  # INFRA-MAR-25: Modify package name to include image suffix if exists
  PACKAGE_NAME: ${{ inputs.package-name }}${{ inputs.image-suffix != '' && format('-{0}', inputs.image-suffix) || '' }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    if: inputs.force || startsWith(inputs.tag, inputs.binary-name) || !inputs.tag && (startsWith(github.ref, format('refs/tags/{0}-v', inputs.binary-name)) || github.ref == 'refs/heads/main' || github.event_name == 'pull_request' || github.event_name == 'merge_group')
    steps:
      # Checking out the repo
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          submodules: 'true'
      - uses: depot/setup-action@v1
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == ${{ env.REPO_NAME }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Generate correct tabs and labels
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          # INFRA-MAR-25: Modify package name to include image suffix if exists
          images: ${{ format('{0}/{1}/{2}', env.REGISTRY, env.REPO_ORG, env.PACKAGE_NAME) }}
          tags: |
            type=ref,event=pr
            type=match,pattern=refs/tags/${{ inputs.binary-name }}-v(.*),group=1,enable=${{ startsWith(env.FULL_REF, 'refs/tags/') }},value=${{ env.FULL_REF }}
            type=sha,format=short
            type=sha,format=long
            # set the actual commit SHA from the PR head instead of from the PR merge commit (alternatively, we could checkout the PR head in actions/checkout)
            type=raw,value=sha-${{ github.event.pull_request.head.sha || github.sha }},enable=${{ startsWith(env.FULL_REF, 'refs/pull/') }}
            # set latest tag for `main` branch
            type=raw,value=latest,enable=${{ env.FULL_REF == format('refs/heads/{0}', 'main') }}
      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          # this gets rid of the unknown/unknown image that is created without this setting
          # https://github.com/docker/build-push-action/issues/820#issuecomment-1455687416
          provenance: false
          context: .
          file: containerfiles/Dockerfile
          build-args: |
            TARGETBINARY=${{ env.FULL_BINARY_NAME }}
          platforms: "linux/amd64,linux/arm64"
          push: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == ${{ env.REPO_NAME }} }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          project: ${{ inputs.depot-project-id }}